name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write # Required for SonarQube PR decoration

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: test
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
